language: python
python: 3.5

before_install:
  docker pull vimc/orderly.server:master

install:
  - pip3 install codecov

script:
  - pip3 install -r requirements.txt
  - coverage run setup.py test

after_success:
  - codecov

services:
  - docker
