language: python
python: 3.5

before_install:
  - env
  - git fetch --unshallow origin/${TRAVIS_BRANCH}
  - ./proxy/build
  - ./proxy/build
  - docker pull vimc/orderly.server:master
  - docker pull vimc/orderly-web:master
  - docker pull vimc/orderlyweb-migrate:master

install:
  - pip3 install codecov

script:
  - pip3 install -r requirements.txt
  - coverage run --source=orderly_web setup.py test

after_success:
  - codecov

services:
  - docker
