#!/usr/bin/env bash
set -e

HERE=$(dirname $0)
. $HERE/common

docker push $APP_DOCKER_BRANCH_TAG
docker push $APP_DOCKER_COMMIT_TAG
docker push $APP_PUBLIC_BRANCH_TAG
docker push $APP_PUBLIC_COMMIT_TAG
