name: Run Tests
on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  run:

    runs-on: ${{ matrix.config.os }}

    name: ${{matrix.config.os }} (${{ matrix.config.py }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  py: '3.8'}
          - {os: ubuntu-latest,  py: '3.9'}
          - {os: ubuntu-latest,  py: '3.10'}
          - {os: ubuntu-latest,  py: '3.11'}
          - {os: ubuntu-latest,  py: '3.12'}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.config.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config.py }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Lint
        run: |
          hatch run lint:all
      - name: Test
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          YOUTRACK_TOKEN: ${{ secrets.YOUTRACK_TOKEN }}
        run: |
          hatch run cov-ci
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          # This can be useful, but the false positive rate is
          # annoyingly high.
          fail_ci_if_error: false
